const assets = {
        tiles:{
            lava:{
                lavaDark:{
                    source:"../Assets/Tiles/Lava/lavaDark.png",
                },
                lavaRed:{
                    source:"../Assets/Tiles/Lava/lavaRed.png",
                },
                woodDark:{
                    source:"../Assets/Tiles/Lava/woodDark.png",
                },
            },
            yellow:{
                plane:{
                    source:"../Assets/Tiles/Yellow/plane.png",
                }
            },
            green:{
                panel:{
                    source:"../Assets/Tiles/Green/panel.png",
                }
            },
            orange:{
                in:{
                    source:"../Assets/Tiles/Orange/in.png",
                }
            },
            blue:{
                out:{
                    source:"../Assets/Tiles/Blue/out.png",
                }
            },
            glases:{
                yellowPlane:{
                    source:"../Assets/Tiles/Glases/yellowPlaneGlases.png",
                    tile:"assets.tiles.yellow.plane.texture"
                },
                lavaDark:{
                    source:"../Assets/Tiles/Glases/lavaDarkGlases.png",
                    tile:"assets.tiles.lava.lavaDark.texture"
                },
                blueOut:{
                    source:"../Assets/Tiles/Glases/blueOutGlases.png",
                    tile:"assets.tiles.blue.out.texture"
                },
                orangeIn:{
                    source:"../Assets/Tiles/Glases/orangeInGlases.png",
                    tile:"assets.tiles.orange.in.texture"
                },
                greenPanel:{
                    source:"../Assets/Tiles/Glases/greenPanelGlases.png",
                    tile:"assets.tiles.green.panel.texture"
                }
            },
         
        },
        sections:{
            greenSection:{
                source:"../Assets/Sections/greenSection.png",
            },
            redSection:{
                source:"../Assets/Sections/redSection.png"
            },
            purpleSection:{
                source:"../Assets/Sections/purpleSection.png"
            },
            pinkSection:{
                source:"../Assets/Sections/pinkSection.png"
            },
            orangeSection:{
                source:"../Assets/Sections/orangeSection.png"
            },
            blueSection:{
                source:"../Assets/Sections/blueSection.png"
            }

        },
        cheeses:{
            cheese1:{
                source:"./Assets/Cheeses/cheese1.png"
            },
            cheese2:{
                source:"./Assets/Cheeses/cheese2.png"
            }
        },
        particles:{
            yellowFlarePolygon:{
                source:"./Assets/Particles/yellowFlarePolygon.png"
            },
            yellowFlare:{
                source:"./Assets/Particles/yellowFlare.png"
            },
            bubble:{
                source:"./Assets/Particles/bubble.png"
            }
        },
        domIcons:{
            iconSoundOn:{
                source:"./Assets/DomIcons/iconSoundOn.png"
            },
            iconSoundOff:{
                source:"./Assets/DomIcons/iconSoundOff.png"
            }
        }
}